apiVersion: v1
kind: Service
metadata:
  name: backend-core
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30100
  selector:
    app: backend-core
  sessionAffinity: None
  type: NodePort